language: java
jdk: oraclejdk8

if: tag IS blank
git:
  depth: 5

install: ./gradlew setupCIWorkspace
script: ./gradlew clean build
after_success: ./gradlew publish

before_cache: find $HOME/.gradle/ -name '*.lock' -print -exec rm -f {} \;
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
